### ISSUE TITLE
Players disappearing from voice channel

### ISSUE THREAD

**Issue by pasindu20** [Tomato6966/erela.js#1]
Players disappearing from voice channel after 12 + hours player connect to channel 
when go that channel and play songs it says no player detected but i destory the players using player.destroy() it will destory 
after usering commands it worked but its so annoying becase if user use command that guilch time it will not work at all

but in https://github.com/Deivu/Shoukaku  i see lot of music bot using it becase of player disappearing form vc this bug is original erela.js
but i try to convert erela code it shoukaku but its too deficalt for me  (i try this on sharded bot)

i see you building erela.js i suggest fix that players disappearing vc

**Comment by Tomato6966** [comment]
so you are saying that the players.get(id) property will say no players?
and when u re-create it, it will?

**Comment by pasindu20** [comment]
> so you are saying that the players.get(id) property will say no players? and when u re-create it, it will?

player.sget(id) say player connected but on discord player not connected if i go player disappeard channel and use player.destroy() it will destroy

**Comment by Tomato6966** [comment]
Never happens too me, you need to add all events like:

channelDelete --> player.destroy()

channelLeave (Bot) --> player.destroy()

channelDisconnect (Bot) --> player.destroy()

playerMove --> player.setVoiceChannel()
