### ISSUE TITLE
finalQuery.match is not a function

### ISSUE THREAD

**Issue by CustomTag** [Tomato6966/erela.js#19]
There is a problem some where in the codes and I can't manages to find it.

its giving me the error that finalQuery.match is not a function this only happens when i'm trying to play a attachment that I upload via the command like this.

Uploading the file via command
![image](https://user-images.githubusercontent.com/65868765/215088166-1bcb34c7-abcc-47a9-a286-4dbbdc218149.png)

so tomato it would be nice if you can find this error for me some how.

Error Down below
![image](https://user-images.githubusercontent.com/65868765/215087982-9a2c479c-392f-46c8-a0cd-4df6db6b9c2b.png)

**Comment by Tomato6966** [comment]
Dear @CustomTag 

Do u have any plugins?

**Comment by CustomTag** [comment]
Do you mean Lavalink Plugins or just erela.js plugins?

If you mean Lavalink plugins I have: LavaSrc, DuncteBot Plugin, xm-plugin
And if you mean erela.js plugins I only have facebook plugin.

@Tomato6966

**Comment by CustomTag** [comment]
I think I found the problem! 

the problem is in the facebook plugin so I removed the plugin and that should fix the issues I guess
