### ISSUE TITLE
What the difference

### ISSUE THREAD

**Issue by pasindu20** [Tomato6966/erela.js#2]
What the difference between original erela.js and this package

**Comment by Tomato6966** [comment]
![image](https://user-images.githubusercontent.com/68145571/177593936-627694a9-f7a5-4211-a950-113a1ace65a9.png)
Check readme....
and a few more..

**Comment by Tomato6966** [comment]
And you have Filters such as player.toggleNightcore()

which allows you to have MULTIPLE FILTERS AT THE SAME TIME
while having EQS too

+ player.position is adjustable

+ volume decrementer
