### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by zoli456** [Tomato6966/erela.js#21]
**onlyAllowAllowedLinks** variable isnt used and I cant use the skybot lavalink plugin to play sounds from additional sources.

**Comment by Tomato6966** [comment]
onlyAllowAllowedLinks was an old variable.

you can use skybot plugin both free and premium version, you can also use lavasrc

**Comment by zoli456** [comment]
Some of the sources havent got regex pattern.(ocremix.org, Clyp.it, Reddit, getyarn.io, soundgasm and PH)

**Comment by Tomato6966** [comment]
You can add your own regexes via the manager#options...
