### ISSUE TITLE
Spotify tracks unable to load (Lavalink V2)

### ISSUE THREAD

**Issue by PixeledLuaWriter** [Tomato6966/erela.js#27]
Hi there, I seem to be having an issue with loading spotify songs through erela.js, i've actually used a plugin called **better-erela.js-spotify** for handling the `UnresolvedTrack` problem the original erela.js had but now it seems like that it doesn't add the song into the queue.

The error that i get whenever i try to load a song is this:
![image](https://github.com/Tomato6966/erela.js/assets/78665021/4d231ceb-36dc-4ac8-b91e-0609132caeb7)

I really have no idea what to do to fix this and this affects both the chat command and slash command that were made for playing the music

**Comment by Tomato6966** [comment]
Use Lavalink V3 with included spotify filters,the problem you are facing is from your erela.js-plugin side.
