### ISSUE TITLE
I can't install the package 

### ISSUE THREAD

**Issue by abood1tameme1** [Tomato6966/erela.js#31]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.

**Comment by CustomTag** [comment]
You have to install git
https://git-scm.com/download/win

**Comment by Tomato6966** [comment]
On linux its `apt-get install git-all`
