### ISSUE TITLE
Switch to poru

### ISSUE THREAD

**Issue by pasindu20** [Tomato6966/erela.js#4]
you are making milarato 2 right so erela.js no longer maintained so change to poru it also like erela.js but it get more update like its the next erela.js(poru) i suggest to switch to poru https://www.npmjs.com/package/poru

**Comment by Tomato6966** [comment]
I think you don't know that there is no reason to switch, if erela.js has supportive of 100% lavalink's feature(s).

All I am doing with this FORK is making it "better" for my needs.
which i would have needed to do with "poru" as well.

**Comment by Tomato6966** [comment]
Also poru is not as efficient as my erela.js version.
