### ISSUE TITLE
Does this support file uploads?

### ISSUE THREAD

**Issue by builtbyjonas** [Tomato6966/erela.js#40]
Hello! I have a question regarding to file uploads like mp3 files. Is it somehow possible to implement that with this package and can someone give me an example for this?

**(this is not a issue, just a question)**

**Comment by Tomato6966** [comment]
If your lavalink server supports it, this client supports it, but check out my new client for up to date features: [lavalink-client](https://github.com/Tomato6966/lavalink-client) as this one isn't maintained anymore.
