### ISSUE TITLE
LavaSrc Spotify issue

### ISSUE THREAD

**Issue by builtbyjonas** [Tomato6966/erela.js#41]
Hello. I have an issue with the Spotify source by the LavaSrc package. It always says:
```
[ ERROR ] Error: Lavalink Node SearchQuerySource: 'spotify' is not available
```
when I try to play / search a song on Spotify. I already contacted the maintainer of the LavaSrc plugin and he told me that LavaSrc is set up correctly and should work fine so he told me to ask here. Does anymbody know a possible solution?

**Comment by Tomato6966** [comment]
use spsearch

**Comment by builtbyjonas** [comment]
> use spsearch

can you send me a link to it please?

**Comment by Tomato6966** [comment]
```
manager.search({
   query: "Hello by Adele",
   source: "spsearch"
})
```


Also you might wna check out my **own client** which is maintained, efficient, feature rich and op:
- [lavalink-client](https://github.com/tomato6966/lavalink-client)


This repository isn't maintained anymore
