### ISSUE TITLE
Add mixcloud to allowedLinksRegexes

### ISSUE THREAD

**Issue by CustomTag** [Tomato6966/erela.js#6]
This is just a tip to add the Mixcloud links to the allowedLinksRegexes so it does not error when its not allowed
You need to have the inbulit Lavalink plugin to use this feature!

Same with the other sources this plugin support to stream it would be help a lot if you add all them to the 
allowedLinksRegexes!

![image](https://user-images.githubusercontent.com/65868765/195117589-7630ce28-a1ae-47a5-82b4-ed59253bbd76.png)
Mixcloud: https://www.mixcloud.com/dashboard/my-dashboard/
Plugin: https://github.com/DuncteBot/skybot-lavalink-plugin

**Comment by Tomato6966** [comment]
merged ur pr
