### ISSUE TITLE
Bot on disconnect doesn't destroy the player

### ISSUE THREAD

**Issue by CASPERg267** [Tomato6966/erela.js#8]
Steps to reproduce

For example i have a player (bot) in the vc if you disconnect the bot it will act as it still in the voice channel
and if you see the player channel is brings null instead of channel id

**Comment by aboshaheen553** [comment]
i have the same problem too

**Comment by Tomato6966** [comment]
you have to handle that yourself.

client.on("voiceStateUpdate", (oldState, newState) => {
   if(oldState.channelId && !newState.channelId) client.musicManager.players.get(newState.guildId)?.destroy?.();
})

**Comment by CASPERg267** [comment]
Ooh completely forgot about this issue, i solved it already
but the reason i opened an issue because it wasn't a bug at original erela.js
